version: "3"

services:
  nodeosd:
    image: liukai:latest
    command: /opt/eosio/bin/nodeosd.sh --delete-all-blocks --genesis-json genesis.json --max-transaction-time=1000 --data-dir /opt/eosio/bin/data-dir -e
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"

  keosd:
    image: liukai:latest
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=0.0.0.0:8900
    hostname: keosd
    ports:
      - 8900:8900
    links:
      - nodeosd
